# Server Configuration
server.port=8080
spring.application.name=transport-grievance-backend
# Database Configuration
#spring.datasource.url=jdbc:mysql://localhost:3306/grievance_management?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=your_password
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true
# File Upload Configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=25MB
file.upload-dir=uploads/complaints
# JWT Configuration
jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
jwt.expiration=86400000
# CORS Configuration
cors.allowed-origins=https://noble-adventure-production.up.railway.app
# Logging
logging.level.com.grievance=DEBUG
logging.level.org.springframework.security=DEBUG
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=deepthiky39@gmail.com
spring.mail.password=voichrgoumlvsqri
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
